### PR TITLE
WIP Add option to choose the default value of keepStaticConnections

### PR DESCRIPTION
**Pull request by jeanlucc**

### CODE REVIEW

**Comment by jeanlucc** [comment]
This PR results from a problem I had when using this really good piece of software to run a whole request in a transaction for integration testing. The connection where initialized when the listeners where initialized on kernel.request, meaning I had to set the value my self either in the Kernel boot or in a dedicated `index_test.php` to avoid messing with my production code.

Although I believe `false` is a sensible default for `StaticDriver::$keepStaticConnections` adding the option to let the user chose this default should not create too many problems.

The solutions is massively inspired by this issue https://github.com/dmaicher/doctrine-test-bundle/issues/111, I want to thank @NicolasGuilloux for the idea and feedback.

@dmaicher Could you let me know what you think of the idea. If you think it's worth it I could improve the PR following your advise.

**Comment by jeanlucc** [comment]
I also adapted the recipe though not mandatory I thought you would like it to be consistent
https://github.com/jeanlucc/recipes-contrib/blob/master/dama/doctrine-test-bundle/4.0/config/packages/test/dama_doctrine_test_bundle.yaml

If you want I could open the merge request (I do not know when these things should be done)

**Comment by dmaicher** [comment]
@jeanlucc thanks for proposing this feature :+1: 

I want to understand some more details about this though.

Can you explain what kind of "integration" test that is? Its a phpunit test? or some other testing lib/tool is used?

**Comment by jeanlucc** [comment]
Hello @dmaicher

First thanks for your time and your response.

I use https://pact.io

Basically the idea is that a pact binary will run real queries to a live server in CI (in my case I use the url of my nginx container that points to php-fpm of my app). To control the state I setup custom data for some calls, I use a listener on kernel request to setup the data before my business logic gets executed.
To do this I use https://github.com/theofidry/AliceDataFixtures and because I think it will be faster than truncate I use no_purge and I use your bundle to create a transaction for the whole request. I could do it like in their documentation https://github.com/theofidry/AliceDataFixtures/blame/master/README.md#L564 a simple `$doctrine->getConnection()->beginTransaction()` but because I found your bundle covered cases I did not want to handle myself in the future I chose to use your bundle to perform the transaction.

Unfortunately in my case the connection is created during the event kernel.request preprocess where some services (connection is one among them) gets instanciated.
There are few places to act before this happens and because I want a solution that does not involve a change in all projects of my company, I thought of this solution.

I hope it is more clear.

**Comment by dmaicher** [comment]
@jeanlucc ok I see. I think this really is an edge case though and not sure I want to expose a config option for this. The bundle is meant to be used in a different way with phpunit :blush: 

I would suggest that you (only for the test environment) register a listener on `kernel.request` that has a very high priority and will be executed before anything else in your app. In there you could then do `StaticDriver::setKeepStaticConnections(true)`. This is a really small fix on your side that should cover this edge-case, or?

**Comment by jeanlucc** [comment]
@dmaicher Yes I agree it is not the primary purpose of the lib. But the fact is I cannot do what you suggest since my problem occurs on preprocess of the event before any listener gets executed.
My only other options are:
- add more configuration into your lib (no breaking change, for my problem it is great and it solve another issue)
- decorate your lib like the previous solution
- modify my kernel boot
- do it in the front controller

If I have to chose I guess I'll end up decorating your decorator which seems sad (in my selfish eyes ;) ) but is the only way I can bundle something since the two other options are not really a good way to make the option reusable.

In fact I did not understand at first why I had to activate the library in configuration and at run time, and then I discovered there were no really elegant way to activate it at run time for my case (and apparently others) thus I tried to create a PR that would allow users to chose a default option that is (again) sensible but prevent to use the bundle in other kind of testing than phpunit

Anyway thank you for your time.

**Comment by jeanlucc** [comment]
Hello I think it may be uncommon tests for your use case. If you want I could explain a bit more about it (maybe on another channel). Here my goal is really this **to isolate your app's doctrine database tests and improve the test performance** it would be like behat tests only with a real instance meaning the classic hooks are not available.

As you may have understood I tried to use a listener, it did not work, I thought of the priority, I went debug the events of my app and I saw the problem occurred on preprocess during the sort of listeners were they are instanciated. I tried to see if there were a point were I could garantee no services were instanciated to make sure I could change this setting and I could not find another way as those mentionned above.
Only after I came to this conclusion I tried to find related issues (event if I understand phpunit is the main goal and it works like a charm for this) I found one and I resolved to propose this feature as I could not see much drawbacks. It is transparent for everyone already using the bundle.

If you do not want to talk more about it, (I understand as you have to maintain this and it takes time), would suggest me a another way to help the users that face a similar issue. Maybe an explanation of what the `StaticDriver::setKeepStaticConnections(true)` is for and when you should do it in a more general cases than phpunit.

Would you say the decoration is a good alternative approach to solve this problem ?

Once again thank you for your time.

**Comment by dmaicher** [comment]
@jeanlucc one other idea could be to use a "service configurator" within a compiler pass:

```php
class ConfigureDAMAConnectionFactoryCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $container->getDefinition('doctrine.dbal.connection_factory')
            ->setConfigurator([ConfigureDAMAConnectionFactoryCompilerPass::class, 'configureFactory']);
    }

    public static function configureFactory(): void
    {
        StaticDriver::setKeepStaticConnections(true);
    }
}
``` 

If you register this compiler pass for the `test` environment only then it should also fix your problem

**Comment by jeanlucc** [comment]
@dmaicher I did not think to use a configurator for this as in fact I do not change the service itself.
Thanks for the idea. I'll dig into that.

It would have been so cool to be able to contribute to this not so big but really really useful piece of software. I guess you can close this now :).

Have a good day.

**Comment by dmaicher** [comment]
> Maybe an explanation of what the StaticDriver::setKeepStaticConnections(true) is for and when you should do it in a more general cases than phpunit.

So the purpose of this boolean flag is that not all the things done with the doctrine connections in the test environment should be transactional.

For example BEFORE I run the phpunit tests in most cases I re-create the database, the schema, insert fixtures etc. This happens in the `test` environment but I don't want the `StaticConnection` for this as it would not work.

So the idea is that this method let's you control when the bundle will actually be "active" for the transaction management of the doctrine connections.

As I see it the bundle provides this functionality for you and you can just use it wherever it fits your use-cases :blush: If you compare the changeset you proposed to the minimal (hopefully working) suggestion with the compiler pass then for me adding this feature is not justified based on this use-case yet.

If there are more use-cases or more people would like to have such an option I will re-visit this :blush: 

Thanks for the time you took to dig into this and let me know if the suggestion above works out :wink:

**Pull request closed without merging**
