### PR TITLE
Document Behat support

### PR DESCRIPTION
**Pull request by mnapoli**
See #48

### CODE REVIEW

**Comment by dkarlovi** [comment]
@mnapoli does this mean you've changed your mind about behat? 😀

**Comment by mnapoli** [comment]
@dkarlovi haha I have to work with Behat for a client. It's OK, but I still think it could be better with PHPUnit (especially since it's an HTTP API with loads of JSON in Gherkin) :)

**Comment by mnapoli** [comment]
@dmaicher good point, just updated the PR!

**Comment by dmaicher** [comment]
Thanks @mnapoli !

**Pull request merged**
