### PR TITLE
Support PHPUnit namespaces

### PR DESCRIPTION
**Pull request by garak**
Since newest PHPUnit switched to namespaces (about time!), we need to follow such change.
This is, of course, a BC break with previous versions.
My advice is, after merging this PR, to create a new branch "1.x" to support legacy versions and to keep dev-master up to date with PHPUnit (so, requiring '^6.0' only). Then, tag a new release next month (when PHPUnit will be stable). In meantime, using dev-master here will be requiring using dev-master on PHPUnit as well.

### CODE REVIEW

**Comment by dmaicher** [comment]
Thanks for the PR! :blush: I actually planned to look into this soon after reading https://twitter.com/s_bergmann/status/814846275099181056.

I will have a look later today and will let you know.

**Comment by dmaicher** [comment]
We also have to change composer to require PHPUnit 6 for 2.x releases then (`"phpunit/phpunit": "~6.0"`). So we have to update the test suite to work with it as well :yum: Currently it needs PHPUnit 4|5. So actually the current master build will fail once PHPUnit 6 will be released because we allow it already :see_no_evil: 

Or what do you think? I can look into adapting the test suite to work with PHPUnit 6.

I would indeed create a `1.x` branch then for `"phpunit/phpunit": "~4.1|~5.0"`.

**Comment by garak** [comment]
I checked twice and indeed we can also use phpunit 5.7, that introduced a forward-compatibility layer for namespaces. So, this PR could also be merged now, working with current stable phpunit, without waiting one month.

**Comment by garak** [comment]
Ah, I see that some classes are missing :cry: 
Opened an [issue](https://github.com/sebastianbergmann/phpunit/issues/2418) on phpunit, fingers crossed!

**Comment by garak** [comment]
As I feared, issue was rejected.
So, I adjusted travis configuration and tests to reflect changes in phpunit 6. I also had to raise requirements to php 7, since phpunit 6 is requiring it (but I think that this is not so bad, php 5 users should be encouraged to upgrade, but they still can use older versions).
Everything is ready. As I previously mentioned, next month, when phpunit 6 stable release will be out, you can tag a `2.0.0` release for this bundle and remove the `minimum-requirement` and `prefer-stable` options from composer.json

**Comment by dmaicher** [comment]
Thanks a lot! :blush: Looks good to me :+1:

**Pull request merged**
