### PR TITLE
README: simplify install

### PR DESCRIPTION
**Pull request by TomasVotruba**
Composer will actually pick the right version based on used PHPUnit version.
And also the one most up to date, compared to old readme text.

### CODE REVIEW

**Comment by dmaicher** [comment]
Indeed you are absolutely right :+1: 

Can you rebase this fix onto `1.x`? I'm usually merging fixes into master from there.

**Comment by TomasVotruba** [comment]
Great!

I tried to point this PR to 1.1 but there were many changes, so it was easier for me to make new PR: https://github.com/dmaicher/doctrine-test-bundle/pull/27

**Comment by TomasVotruba** [comment]
Just at ip: I would expect to have default branch as one to send PRs to. It would prevent this issue to have 1.1 right from the start.

**Comment by dmaicher** [comment]
well its a bit similar to other repositories as well :wink: 
For example on `symfony/symfony` you create a PR on the lowest branch where it applies as also there changes are merged from lower to higher branches.

But anyway you could not know how I handle it so all good :blush: :+1:

**Comment by TomasVotruba** [comment]
> well its a bit similar to other repositories as well

Only at first sight, but actually not at all. Symfony has 2+ branches, that you could send PRs too. So you have to really think about it, where to send it. 

If it would have just one (`1.1` in your case), it should be the one users see by default. I've already seen many duplicated PRs to `master` and the other branch, just because of this.

> But anyway you could not know how I handle it so all good :blush: :+1:d

Yea, it's just redundant work for me, that can be solved by Github setup. That's all, no problem :+1:

**Comment by dmaicher** [comment]
As I indeed only have 2 branches and all changes should go to `1.x` anyway for now I changed the default branch to make it more obvious :+1:

**Comment by TomasVotruba** [comment]
Thank you, that's just great :heart: 

I see min dependency is PHP 7.1, would like to have `script_types` added?

**Comment by dmaicher** [comment]
You mean `strict_types=1`? Actually I think its fine in "weak mode" :wink: But thanks anyway.

**Comment by dmaicher** [comment]
Btw does the bundle work nicely for you? Always interested in hearing feedback :smile:

**Comment by TomasVotruba** [comment]
Allright.

It does! I actually don't use, just came by accident :laughing:

**Pull request closed without merging**
